### PR TITLE
Implement reversed grant checking methods

### PR DESCRIPTION
**Pull request by ladydascalie**
As per comments made in #68

### CODE REVIEW

**Comment by zeevallin** [comment]
I think that using the wording `Any` is confusing the intent of the function. Does it mean that it should return true if any of them is not present? I would suggest using method names like `MissingAll`, `MissAll` or `LackAll` would be more appropriate.

```go
if consumer.LackAllRoles("admin", "guest") {
    return fmt.Errorf("the consumer does not have any of the roles required")
}
if consumer.MissAllRoles("admin", "guest") {
    return fmt.Errorf("the consumer does not have any of the roles required")
}
if consumer.MissingAllRoles("admin", "guest") {
    return fmt.Errorf("the consumer does not have any of the roles required")
}
```

I think we should add a third one for needs as well, while we're at it.

**Review by zdjones — DISMISSED** [review]
Agree with the naming confusion.

These return false as soon as they find one match, which sounds more like MissesAllGrants, which I think is the same as !HasAnyGrant.

To me, MissesAnyGrant says "there is at least one missed grant". For that you'd have to check until you fail to find a match, then return true.

That being said, I think !HasAnyGrant describes the test better. I would go with:
```
if consumer.NotHaveAnyGrant("admin", "guest") {
    return fmt.Errorf("the consumer does not have any of the grants required")
}
//or
if consumer.GrantsNotOneOf("admin", "guest"){
    return fmt.Errorf("the consumer does not have any of the grants required")
}
```
It even reads the same as @zeeraw 's error

**Comment by zeevallin** [comment]
I agree with @zdjones, the original method name is more clear to me when just negating what it does. What about `NotOneOfGrants`?

**Comment by ladydascalie** [comment]
Following this conversation, I've settled on a `HasNoMatching{Role|Grant|Need}` naming convention which more closely follows the existing, and is way more expressive

**Comment by zeevallin** [comment]
nice.

**Review by zeevallin — APPROVED** [review]

**Pull request merged**
